Add function whose return data from .tcx files
Open-Health-Data-Project/hdp pull request #4
Opened 2020-07-01 14:34 UTC by nero2310

This function return data as Datatable object list, aslo return
Dictonary with exceptions

2020-07-01 15:52 UTC, mdyzma requested changes

2020-07-01 15:52 UTC, mdyzma commented on hdp/process/load.py
>  def load_jpg(jpg_files: list, params: dict):
This function ddoes not do anytjhing Use YAGNI (you are not gonna need it). Please, do not place code without function.

I suggest use Project tab and create issue/bug.

2020-07-01 15:52 UTC, mdyzma commented on hdp/process/load.py
> +                                point[value.name] = value.text.strip()
Too complicated/nested function, try to extract to higher level function.

i.e.:

`def extract_path():
    pass`


```python
def extract_all_trackpoints(node_name="trackpoint"):
    for trackpoint in activity.find_all(node_name):
        points = {element.name: element.text for element in trackpoint.children if
             isinstance(element, Tag) and len(element.findChildren()) == 0}
    return points

def extract_points(trackpoints):
    point = {}
    for element in trackpoints.children:
        if isinstance(element,Tag) and len(element.findChildren())>1:
            for value in element.children:
                if isinstance(value,NavigableString):
                    point[value.name] = value.string
                elif isinstance(value,Tag):
                    point[value.name] = value.text.strip()
    return point
```

If it still complains refactor further.

2020-07-01 15:52 UTC, mdyzma commented on hdp/process/load.py
> +
Import proper typing suggestions
```suggestion
from typing import List, Tuple, Dict
```

2020-07-01 15:52 UTC, mdyzma commented on hdp/process/load.py
>  def load_tcx(tcx_files: list, params: dict):
```suggestion
def load_tcx(tcx_files: List[str], params: Dict) -> Tuple:
```

2020-07-02 14:29 UTC, nero2310 commented on hdp/process/load.py
> +                                point[value.name] = value.text.strip()
Should I define auxiliary functions inside load_tcx or outside?

2020-07-02 16:36 UTC, mdyzma commented
Outside

czw., 2 lip 2020, 16:30 użytkownik nero2310 <notifications@github.com>
napisał:

> *@nero2310* commented on this pull request.
> ------------------------------
>
> In hdp/process/load.py
> <https://github.com/Open-Health-Data-Project/hdp/pull/4#discussion_r449043964>
> :
>
> > +    activites = []
> +    for path in tcx_files:
> +        try:
> +            name = _get_file_name(path)
> +            with(open(path,"r")) as file:
> +                activity = BeautifulSoup(file,'lxml')
> +            for trackpoint in activity.find_all("trackpoint"):
> +                point = {element.name: element.text for element in trackpoint.children if
> +                         isinstance(element, Tag) and len(element.findChildren()) == 0}
> +                for element in trackpoint.children:
> +                    if isinstance(element,Tag) and len(element.findChildren())>1:
> +                        for value in element.children:
> +                            if isinstance(value,NavigableString):
> +                                point[value.name] = value.string
> +                            elif isinstance(value,Tag):
> +                                point[value.name] = value.text.strip()
>
> Should I define auxiliary functions inside load_tcx or outside?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Open-Health-Data-Project/hdp/pull/4#discussion_r449043964>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABV5Z5EMSATG5GBGZFZN3ZTRZSKWTANCNFSM4ONPI4YA>
> .
>

2020-07-02 23:38 UTC, nero2310 commented on hdp/process/load.py
>  def load_jpg(jpg_files: list, params: dict):
Do you mean this load_jpg function? I am pretty sure this is empty for a purpose.

2020-07-07 20:09 UTC, merged