Team3
Open-Health-Data-Project/hdp pull request #5
Opened 2020-07-10 19:05 UTC by nero2310

load_gpx function

2020-07-10 20:26 UTC, KrzysiekDev commented on hdp/process/load.py
> +def extract_waypoints(gtx_parsed):
Change `gtx_parsed` to `gpx_parsed`.
I was wondering if we need waypoints, but maybe we can load them.

2020-07-10 20:27 UTC, KrzysiekDev requested changes
You need to change typo in one place.

2020-07-11 00:17 UTC, nero2310 commented on hdp/process/load.py
> +def extract_waypoints(gtx_parsed):
Oh is a misspelling, I think we should load them just in case we wanna use them.

2020-07-11 11:03 UTC, KrzysiekDev approved these changes
Now it's OK.

2020-07-13 17:50 UTC, KrzysiekDev approved these changes
Looks OK.

2020-07-13 17:55 UTC, merged